server:
  port: 8762
  error:
    include-stacktrace: never
spring:
    main:
      web-application-type: reactive
    application:
      name: api-gateway
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        routes:
          #Database ImageService
          - id: image-service
            uri: lb://image-service
            predicates:
              - Path=/user/**
              - Method=GET
          # Database AdminService
          - id: Admin-Service
            uri: lb://Admin-Service
            predicates:
              - Path=/api/Admin/**
              - Method=GET,POST, PUT, DELETE
          # Database GalleryService
          - id: gallery-service
            uri: lb://gallery-service
            predicates:
              - Path=/client/**
              - Method=GET
          # Database Location
          - id: Location-Service
            uri: lb://Location-Service
            predicates:
              - Path=/content/**
              - Method=GET,POST, PUT, DELETE
          - id: Location-Service
            uri: lb://Location-Service
            predicates:
              - Path=/locations/**
              - Method=GET,POST, PUT, DELETE
          - id: Location-Service
            uri: lb://Location-Service
            predicates:
              - Path=/Detail/**
              - Method=GET,POST, PUT, DELETE






